# Generated by Django 2.2 on 2020-04-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origanizations', '0002_auto_20200411_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
