# Generated by Django 2.2 on 2020-04-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '视频资源', 'verbose_name_plural': '视频资源'},
        ),
    ]
