# Generated by Django 2.2 on 2020-04-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origanizations', '0004_auto_20200419_1754'),
        ('courses', '0002_auto_20200419_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origanizations.CourseOrg', verbose_name='课程机构'),
        ),
    ]
